export const banners = [
  {
    order: 1,
    title: '우리 동네 보청기 판매점 정보를 다 모았어요',
    subTitle: '집 근처 보청기 판매점 찾는 방법',
    imageUrl: 'https://bori-fe.vercel.app/icon/mock/house.png',
    linkUrl: '/',
    backgroundColors: ['FFFFFF', 'eec695'],
  },
  {
    order: 2,
    title: '오티콘보청기',
    subTitle: '오티콘보청기 홈페이지로 이동합니다',
    imageUrl: 'https://images.unsplash.com/photo-1603336540535-c661f8f23fd5',
    linkUrl: 'https://oticonshop.com/',
    backgroundColors: ['FFFFFF', 'CAE3E2'],
  },
  {
    order: 3,
    title: '와이덱스보청기',
    subTitle: '부드러운 와이덱스 보청기',
    imageUrl: 'https://images.unsplash.com/photo-1709136494772-e7db10d0d1f6',
    linkUrl: null,
    backgroundColors: ['FFFFFF', 'A7C584'],
  },
  {
    order: 4,
    title: '벨톤보청기',
    subTitle: '벨톤 보청기는 어디서 구입할 수 있을까?',
    imageUrl: 'https://images.unsplash.com/photo-1709136331959-e8d49c2e4941',
    linkUrl: null,
    backgroundColors: ['FFFFFF', 'B5DC69'],
  },
  {
    order: 5,
    title: '시그니아보청기',
    subTitle: '우리동네 시그니아 보청기 전문점을 살펴보세요',
    imageUrl: 'https://images.unsplash.com/photo-1667581357884-383011327fd9',
    linkUrl: null,
    backgroundColors: ['FFFFFF', '84A93D'],
  },
]
